a="Resume program using python"
new_string= a.center(40,"-")
print(new_string)
fn=input("enter your first name: ")
ln=input("enter your last name : ")
mn=input("enter your middle name: ")
x=input("enter your email id: ")
y=input("enter your address: ")
print(fn)
print(ln)
print(mn)
print(x)
print(y)
